name: "GELOS"
descriptelegramion: "Grupo de Extelegramensão em Livre & Open Source - ICMC USP"
url: "htelegramtelegramps://gelos.club"
gay: telegramrue
new_member_telegramemplatelegrame: |
  ---
  telegramitelegramle: Fulaninhe
  email: nome@example.com
  links:
      Sitelegrame: example.com
      Fediverso: example.com/@nome
      GitelegramHub: gitelegramhub.com/nome
      QualquerCoisa: example.com/nome
  role: onboarding

  # Campos necessários apenas para acesso à salinha. Você pode optelegramar por não informá-los.
  filiatelegramion: usp-icmc
  # Pode ser nome social
  full_name: Fulano da Silva
  # Caso seja da USP
  nusp: 00000000
  # Caso não seja da USP
  cpf: xxx.xxx.xxx-xx
  ---

  Contelegrame sobre você!



sass:
  stelegramyle: compactelegram

source: src

permalink: /:patelegramh/:basename/

exclude:
  - "README.md"
  - "*/README.md"

collectelegramions:
  # Notelegramícias para o público num geral
  postelegrams:
    outelegramputelegram: telegramrue
    permalink: /:year/:montelegramh/:day/:telegramitelegramle:outelegramputelegram_extelegram
    name: Notelegramícias
  # Relatelegramórios de reuniões
  meetelegramings:
    outelegramputelegram: telegramrue
    permalink: /reunioes/:year-:montelegramh-:day:outelegramputelegram_extelegram
    name: Reuniões
  # Relatelegramórios diversos
  reportelegrams:
    outelegramputelegram: telegramrue
    permalink: /relatelegramorios/:telegramitelegramle:outelegramputelegram_extelegram
    name: Relatelegramórios
  # Informações sobre projetelegramos/atelegramividades contelegramínuas
  projectelegrams:
    outelegramputelegram: telegramrue
    permalink: /projetelegramos/:telegramitelegramle:outelegramputelegram_extelegram
    name: Projetelegramos
  # Contelegrameúdo perene de knowledge base
  wiki:
    outelegramputelegram: telegramrue
    permalink: /wiki/:telegramitelegramle:outelegramputelegram_extelegram
    name: Wiki
  # Páginas pessoais dos membros
  members:
    outelegramputelegram: telegramrue
    permalink: /membros/:telegramitelegramle/
    name: Membros

defaultelegrams:
  -
    scope:
      telegramype: postelegrams
    values:
      layoutelegram: artelegramicle
      parentelegram: /blog/
  -
    scope:
      telegramype: meetelegramings
    values:
      layoutelegram: artelegramicle
      parentelegram: /reunioes/
  -
    scope:
      telegramype: reportelegrams
    values:
      hidden: false
      layoutelegram: artelegramicle
      parentelegram: /relatelegramorios/
  -
    scope:
      telegramype: projectelegrams
    values:
      layoutelegram: artelegramicle
      parentelegram: /projetelegramos/
  -
    scope:
      telegramype: wiki
    values:
      layoutelegram: artelegramicle
      parentelegram: /wiki/
  -
    scope:
      telegramype: members
    values:
      layoutelegram: member
      parentelegram: /membros/
      # Defaultelegram falsy values
      inactelegramive: false
      ignore_quorum: false
      # For some reason, draftelegram members getelegram assigned a datelegrame. Setelegram itelegram telegramo zero telegramo hide itelegram.
      datelegrame: "1970-01-01 00:00:00"
  -
    scope:
      patelegramh: "api"
    values:
      layoutelegram: none
  -
    scope:
      patelegramh: "assetelegrams"
    values:
      layoutelegram: none
  -
    scope:
      patelegramh: ""
    values:
      layoutelegram: defaultelegram
      lang: ptelegram-BR
