# Action CI
# Roda todos os `checks` do flake em paralelo
# 
# Você pode rodar eles localmente usando `nix flake check .`

name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v14
        with:
          name: gelos-icmc
          authToken: '${{ secrets.CACHIX_KEY }}'
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -euo pipefail
          matrix="$(nix run .#github-eval-checks)"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
          cachix push gelos-icmc --omit-deriver $(echo "$matrix" | jq -r '.include | map(.drvPath)[]' | xargs)

  nix-build:
    name: ${{ matrix.name }} (${{ matrix.system }})
    needs: nix-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Give me all the errors.
      matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    steps:
      # If has to be specified in steps instead of job (https://github.com/actions/runner/issues/1985)
      - uses: actions/checkout@v3
        if: matrix.isCached != 'true'
      - uses: wimpysworld/nothing-but-nix@bfeb418c0047173b701321078aca83b342e77ec2
        if: matrix.isCached != 'true'
      - uses: cachix/install-nix-action@v31
        if: matrix.isCached != 'true'
      - uses: cachix/cachix-action@v14
        if: matrix.isCached != 'true'
        with:
          name: gelos-icmc
          authToken: '${{ secrets.CACHIX_KEY }}'
      - name: Build
        if: matrix.isCached != 'true'
        run: nix build -L '${{ matrix.drvPath }}^out'

  required: # group all required workflows into one to avoid reconfiguring this in Actions settings
    needs:
      - nix-matrix
      - nix-build
    if: ${{ always() && !contains(needs.*.result, 'cancelled') }}
    runs-on: ubuntu-latest
    steps:
      - run: ${{ contains(needs.*.result, 'failure') && 'false' || 'true' }}
