# Action CI
# Roda todos os `checks` do flake em paralelo
# 
# Você pode rodar eles localmente usando `nix flake check .`

name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
jobs:
  # Pula a CI se ela já rodou em algo com o exato mesmo conteúdo
  skip-check:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.skip-check.outputs.skip-check }}
    steps:
      - uses: cariad-tech/merge-queue-ci-skipper@1032489e59437862c90a08a2c92809c903883772
        id: skip-check

  nix-matrix:
    needs: skip-check
    if: needs.skip-check.outputs.skip != 'true'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v31
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -euo pipefail
          matrix="$(nix eval --json '.#githubActions.matrix')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
          echo "$matrix" | jq

  nix-build:
    name: ${{ matrix.name }} (${{ matrix.system }})
    needs: nix-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Give me all the errors.
      matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
      - uses: wimpysworld/nothing-but-nix@bfeb418c0047173b701321078aca83b342e77ec2
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v14
        with:
          name: gelos-icmc
          authToken: '${{ secrets.CACHIX_KEY }}'
      - name: Build
        run: |
          if curl "https://gelos-icmc.cachix.org/$(nix eval --raw '.#${{ matrix.attr }}.outPath' | cut -d / -f4 | cut -d - -f1).narinfo"; then
            echo "Package is already cached, skipping"
          else
            nix build -L '.#${{ matrix.attr }}'
          fi

  required: # group all required workflows into one to avoid reconfiguring this in Actions settings
    needs:
      - nix-matrix
      - nix-build
    if: ${{ always() && !contains(needs.*.result, 'cancelled') }}
    runs-on: ubuntu-latest
    steps:
      - run: ${{ contains(needs.*.result, 'failure') && 'false' || 'true' }}
