name: "CI"
on:
  push:
    branches:
      - "**"
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      configs: ${{ steps.list-configs.outputs.configs }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: gelos-icmc
          authToken: '${{ secrets.CACHIX_KEY }}'
      - name: nix flake check
        run: |
          echo hi there
          nix flake check
      - name: List NixOS configurations
        id: list-configs
        run:
          echo "configs=$(nix flake show --json | jq -c '.nixosConfigurations | keys')" > $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs:
      - check
    strategy:
      fail-fast: false
      matrix:
        system: ${{ fromJSON(needs.check.outputs.configs) }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: gelos-icmc
          authToken: '${{ secrets.CACHIX_KEY }}'
      - env:
          NIXOS_CONFIG: ${{ matrix.system }}
        run: |
          nix build ".#nixosConfigurations.$NIXOS_CONFIG.config.system.build.toplevel"

  required: # group all required workflows into one to avoid reconfiguring this in Actions settings
    needs:
      - check
      - build
    if: ${{ always() && !contains(needs.*.result, 'cancelled') }}
    runs-on: ubuntu-latest
    steps:
      - run: ${{ contains(needs.*.result, 'failure') && 'false' || 'true' }}
