# Action Deploy
# Roda `apps.deploy`
# 
# Você pode executar isso localmente usando `nix run .#deploy`
# (Requer uma chave SSH autorizada nos hosts)

name: "Deploy"
on:
  push:
    branches: [ main ]
concurrency:
  group: ${{ github.workflow }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Prod
    steps:
      - uses: actions/checkout@v3
      - uses: wimpysworld/nothing-but-nix@bfeb418c0047173b701321078aca83b342e77ec2
        with:
          nix-permission-edict: true
      - uses: nixbuild/nix-quick-install-action@v30
      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: ${{ matrix.platform.system }}
      - uses: cachix/cachix-action@v14
        with:
          name: gelos-icmc
          authToken: '${{ secrets.CACHIX_KEY }}'
      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Deploy
        run: nix run .#deploy -- --skip-checks
